module.exports= {
    NEWBORN_COMPLICATIONS_ASPHYXIA: 'vcEWpcFjEuU',
    NEWBORN_COMPLICATIONS_NONE: 'SytVoNgDYlf',
    NEWBORN_COMPLICATIONS_OTHER: 'Z9Q4qIjoePS',
    NEWBORN_COMPLICATIONS_PREMATURITY: 'UXTZkim1Np',
    NEWBORN_COMPLICATIONS_SEPSIS: 'bPvw8ZdBgRe',
    NEWBORN_COMPLICATIONS_LBW: 'gkgM1TgE5oF',

    NEWBORN_COMPLICATIONS_MNGT_ANTIBIOTICS: 'mWeTHZCPNT0',
    NEWBORN_COMPLICATIONS_MNGT_KMC: 'zANGFtNoUEt',
    NEWBORN_COMPLICATIONS_MNGT_OTHER: 'qYKuaHC8Gnk',
    NEWBORN_COMPLICATIONS_MNGT_RESC: 'zE0WLBSHx1e',

    NEWBORN_SURVIVAL_PMTCT_ALIVE_EXP_NO_NVP: 'EeywK6AHQdK',
    NEWBORN_SURVIVAL_PMTCT_ALIVE_EXP_NVP_STARTED: 'iBBnHx1Uf50',
    NEWBORN_SURVIVAL_PMTCT_ALIVE_NEONATAL_DEATH: 'jz793Wzon1W',
    NEWBORN_SURVIVAL_PMTCT_ALIVE_NOT_HIV_EXP: 'q7NoDcfaciO',
    NEWBORN_SURVIVAL_PMTCT_ALIVE_STILL_FRESH: 'YlydKJIyGFF',
    NEWBORN_SURVIVAL_PMTCT_ALIVE_UNKOWN_EXP: 'kaYz6eqxqQH',
    NEWBORN_SURVIVAL_PMTCT_ALIVE_STILLBIRTH_MASCERATED: 'EJ0qYm1FrcH',

    ROUTINE_CARE_CHLOROHEXIDINE_GIVEN: 'YvNy8rie5j7',
    ROUTINE_CARE_ITN_GIVEN: 'NNFGzJD43R9',
    ROUTINE_CARE_VITK_GIVEN: 'zAcW94iEdXU',
    ROUTINE_CARE_TETRACYCLINE_GIVEN: '',

    BREAST_FEEDING_INITIATED: '',
    BREAST_FEEDING_INITIATED_NEVER_OR_LATER_THAN_60: '',
    BREAST_FEEDING_INITIATED_BFORE_60_MINS: ''

}